import "../globals.css";
// 1. Import the component
import BottomNav from "../_components/Bottomnav";
import { Providers } from "../_components/Provider";


export const metadata = {
  title: "Sky-It",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
      <div
        className={` antialiased  `} 
        
      >

        
        <Providers>
        {children}

        </Providers>
        
        {/* 2. Add the Navigation here */}
        <BottomNav />
        
      </div>
   
  );
}